### ISSUE TITLE
Action to prevent laptop from sleeping

### ISSUE THREAD

**Issue by Prodeguerriero** [G-dH/custom-hot-corners-extended#103]
Hi there,

I have been looking at the list of actions for one that would allow me to prevent my laptop from going to sleep. Either I am not using the right keyword, or the action doesn't exist. Can you tell me if it is the former or the latter?

If the latter, do you think it could be added in the future? Something like what [KeepAwake](https://github.com/jenspfahl/KeepAwake) does. But I'd prefer the hot corner solution, so that I don't have to worry about forgetting to turn the feature off.

Cheers, and thanks for the hard work.

**Comment by G-dH** [comment]
Hi. I'm not sure how a hot corner could help you remember. I believe that dedicated extensions offer better service, allowing you to trigger the "keep awake" function for a period of time or for a particular application, like the Caffeine extension. However, I can add support for an extension that provides an API to control it externally.

**Comment by Prodeguerriero** [comment]
> Hi. I'm not sure how a hot corner could help you remember.

Hi. It's not that the hot corner would help me remember, it would help me by not having to remember at all.

In other words, I see it more as a "push and hold" scenario. The moment I "release", i.e., move the cursor, the feature is tutned off. 

> I believe that dedicated extensions offer better service, allowing you to trigger the "keep awake" function for a period of time or for a particular application, like the Caffeine extension. However, I can add support for an extension that provides an API to control it externally.

Fair enough.

**Comment by G-dH** [comment]
> In other words, I see it more as a "push and hold" scenario. The moment I "release", i.e., move the cursor, the feature is tutned off.

Aha, that’s not a bad idea. If you can convince the author of such extension to add a public API, I can implement it.

**Comment by Prodeguerriero** [comment]
> Aha, that’s not a bad idea. If you can convince the author of such extension to add a public API, I can implement it.

I realize I'm in no position to ask for this, but wouldn't it be easier to check which Gnome settings the extension triggers, and create a standalone action? I'm saying this mainly to avoid having a dependency with another app.

Anyway, I'll reach out and ask them, let's see what they think. Any specifications I should share with them?

**Comment by G-dH** [comment]
You can ask them to implement the "hot" corner feature directly into their extension. It's easy to implement and since I'm developing and maintaining several non-trivial extensions, my to-do list is long and time is short... ;)

**Comment by G-dH** [comment]
In addition, with the CHC-E interface, there would be a problem explaining the proposed feature to the users ...

**Comment by Prodeguerriero** [comment]
All fair points. I think the easiest solution is to simply use the other extension. But I will drop an issue in the Caffeine extension, see if they want to entertain the idea. Feel free to close this one if you want.

**Comment by Prodeguerriero** [comment]
I think this can be closed for now. The issue I opened for the Caffeine extension has been marked as a feature request. If they need you, they will know where to find you. Cheers.

**Comment by G-dH** [comment]
👍
