### ISSUE TITLE
Custom hot edges

### ISSUE THREAD

**Issue by msadeqhe** [G-dH/custom-hot-corners-extended#13]
I hope you add a feature to make it possible to define actions for custom hot edges in addition to hot corners. Custom hot edges will allow us to easily switch between desktops by moving the mouse pointer to the middle of left / right edges, or we can use the middle of top / bottom edges. Also custom hot edges may have barrier size (edge to corner expansion).
Currently we have 4 hot corners, it would be amazing if you allow us to have another 4 hot edges, in total 8 hot zones for different actions with total control over the edges / corners of the screen.
Your extension is really helpful, thanks.

**Comment by G-dH** [comment]
Hi, maybe later, too many things I'd like to do...

**Comment by adsick** [comment]
Hi, I'm here to say that I'd like to have hot edges as well as you ;)

**Comment by LaKing** [comment]
There seem to be a gnome extension handling hot corners, aware of on screen keyboard

**Comment by pc00per** [comment]
The best way to do this right now, is to expand one of the corner to either bottom / top (depending on it's position) & assign shortcut there.

**Comment by G-dH** [comment]
CHC-E is already complex enough, separate hot edges are not on the to-do list for now.
