### ISSUE TITLE
How to trigger Arc Menu (default app menu in Manjaro Gnome)?

### ISSUE THREAD

**Issue by zilexa** [G-dH/custom-hot-corners-extended#14]
Since I use a vertical panel on the left side, I have the application menu (Arc Menu) in the top left.
I would like to set Top Left hot corner to open the menu, so that I don't have to click it anymore.

I went through all options, also custom command preset (choosing an application) but I cannot find it anywhere. 

How can I trigger this action?

In Arc Menu settings, I already set the (left) Super key (Win) to open this menu as well.

**Comment by G-dH** [comment]
Arc menu is not an application, it's an extension of Gnome Shell and runs as a part of it, therefore It has no app launcher. It could be triggered by a js command directly from the Gnome Shell's code, but it's not that simple without reviewing the code of the extension. If find the way, I'll let you know.

**Comment by zilexa** [comment]
Thanks for the help, I also posted this question here: https://forum.manjaro.org/t/what-is-the-official-recommended-solution-to-add-gnome-support-for-other-hot-corners/82371/6?u=zilexa
Perhaps someone who knows the code of this particular aspect has an idea that can help.

**Comment by G-dH** [comment]
Added support for ArcMenu in commit 11002a031c46f88457a714670cd891b4565e2735
