### ISSUE TITLE
Show Application Grid shortcut conflicts with Dash-to-Dock

### ISSUE THREAD

**Issue by gdiShun** [G-dH/custom-hot-corners-extended#15]
Having a weird conflict between 3 plugins. Going to probably post this to the others so wording this so I can easily copy-and-paste.

So the plugins are [Dash-to-Dock](https://micheleg.github.io/dash-to-dock/), [Custom Hot Corners - Extended](https://github.com/G-dH/custom-hot-corners-extended), and [Just Perfection](https://gitlab.gnome.org/jrahmatzadeh/just-perfection).

So what happens is that when Dash-to-Dock is enabled, and I use the Show Applications Grid shortcut in Custom Hot Corners - Extended, the screen will flicker for a few frames, like it's trying to show the application grid, but then it fails to do so. From there, after that happens, if I open the Application Grid through other means, like using the Super+A keyboard shortcut, the Grid and the Overview will not recognize my mouse at all. The only way to fix this is to either reboot, or disable Just Perfection.

Unfortunately, there's nothing I can find in the logs about this. It just happens. What I do know is that Dash-to-Dock needs to be enabled for the initial shortcut to fail. I didn't test extensively, but it appears to only be with the Show Application Grid shortcut. The Grid/Overview mouse problem is only there if Just Perfection is enabled. I couldn't find any individual settings in Just Perfection that would disable it. The entire plugin has to be disabled.

**Comment by G-dH** [comment]
This issue was addressed in commit [dc766a26ac1198dd13e7b8b6348919946a9548fd](https://github.com/G-dH/custom-hot-corners-extended/commit/dc766a26ac1198dd13e7b8b6348919946a9548fd#diff-3b72b7f28f852d87e6820f3169ff8cdfba710182a586363cc467e9b1602c528a), I forgot to add it to the commit message.
