### ISSUE TITLE
separate Ctrl bindings

### ISSUE THREAD

**Issue by adsick** [G-dH/custom-hot-corners-extended#16]
Hi, awesome extension bro. I'd like to be able to bind modkeys separately, so we could have many variants of bindings and have many actions to perform.

e.g. just point to a corner/edge does X, but doing the same with Ctrl pressed does Y. Also you can add more modifiers like Shift and Alt, that would be really awesome!

**Comment by G-dH** [comment]
Too many options you want, the prefs window is overwhelming already for most people. When I realize that I need it, I'll do it ;)

**Comment by G-dH** [comment]
Anyway, thanks for the input! The truth is that I myself have been thinking about separate actions for hot corners and Ctrl + hot corners, even about those edges, but my main problem is that the combo box menus are painfully slow and buggy (now it's 875 menu items for each corner and I can't fill all combos at once if I don't want the user to wait seconds for the preferences window). I need to solve this first..

**Comment by adsick** [comment]
I see. 
Ok, maybe some time in the future

**Comment by G-dH** [comment]
I solved the slow combo issue and added the trigger for hot corners - now you can set one action for the hot corner without Ctrl and the second one with Ctrl pressed.

**Comment by adsick** [comment]
Nice, time to install it back!
