### ISSUE TITLE
Add media playback control

### ISSUE THREAD

**Issue by re64trh5hheterrethg** [G-dH/custom-hot-corners-extended#18]
Thanks for this wonderful extension! :heart: 
Would it be possible to add media playback control, in addition to existing sound control?
![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi1.wp.com%2Fitsfoss.com%2Fwp-content%2Fuploads%2F2018%2F11%2Faudio-control-system-tray-gnome-1.jpeg%3Fresize%3D800%252C419%26ssl%3D1&f=1&nofb=1)
That would allow changing Spotify music, and switching to next track when current one doesn't correspond to the user mood :-)
Found this [old extension](https://github.com/Caccc/Gnome-shell-extension-Mediasplayers/blob/master/mediasplayers%40ycdref/extension.js#L262) that may help but development is above my understanding.

**Comment by G-dH** [comment]
Hi, thanks for the feedback! I'll look into it and let you know.

**Comment by G-dH** [comment]
`Sound` menu renamed to `Media`
Added actions:
`Media key - Play/Pause`
`Media key - Next Track`
`Media key - Previous Track`
Commit: bac5111be4b84b2b9a872e078c024e50f5c9bb45
