### ISSUE TITLE
One App Overview

### ISSUE THREAD

**Issue by Nico7as** [G-dH/custom-hot-corners-extended#20]
Could It be possible to add an option for an overview of a single app, running several windows.

For exemple, when the Files App has several windows opened, and active, the One App Overview would show only these windows, leaving the other running apps blurred in the background.
macOS does it, and it's really convinient.

cheers

**Comment by G-dH** [comment]
Modifications of the overview is a task for other extension. However, if you install [AATWS - Advanced Alt-Tab Window Switcher](https://extensions.gnome.org/extension/4412/advanced-alttab-window-switcher/) extension, then the CHC-E adds new items to its `Window/App Popup Switcher` actions menu in the preferences window and you could be able to trigger the switcher popup with the content you're interested in. AATWS if extremely configurable and can even filter windows by typing.
