### ISSUE TITLE
Let through click events that are not mapped in the extension

### ISSUE THREAD

**Issue by UndeadDevel** [G-dH/custom-hot-corners-extended#21]
First of all: great extension! It really enhances the Gnome experience!

There is one problem, however, and I'd like to make one request:

The problem is that the extension intercepts mouse click events of all kinds if the relevant slider is set, which becomes an issue when extending the border of one of the right corners to the right side and using that side for, e.g., window switching via mouse scrolling, because now, even though I haven't mapped left click there (only middle mouse click and scrolling), moving the mouse to the right side and clicking on scroll bars to jump down in a page in a maximized window will often result in the click not having an effect, because it is intercepted.
So it would be nice if only those mouse events that are mapped in the extension could be intercepted and others let through.

The (unrelated) request is that the Gnome actions "View split on left" and "View split on right" (typically Super + Left Arrow / Right Arrow in Settings) be added under "Windows - Control" since that is the only thing I'm missing out of the many good choices there.

Thank you for your work!

**Comment by G-dH** [comment]
Hi, thanks for the feedback. I'll try to fix the mouse events issue and add the actions.

**Comment by G-dH** [comment]
However, I remember I've decided a long time ago that the 'snap window to half of the screen' actions are unnecessary, since you can just drag and drop the window to the edge of the screen...

**Comment by UndeadDevel** [comment]
Hmm good point; I guess that's just about as convenient as the way I planned to do it with this extension...feel free to ignore that part then.

I did discover another issue, however; I'll open it in a moment.

**Comment by G-dH** [comment]
This would be nice to fix, but I don't know how yet.

**Comment by G-dH** [comment]
This issue has probably no solution. Actors that are responsible for catching mouse events are (and must be) in a different stage than other desktop objects and therefore the events can't be propagated to objects below.

**Comment by pc00per** [comment]
Btw it's really not needed as you don't care about background objects when you assign hot corners there. Afaik that's how my use case is.

**Comment by G-dH** [comment]
@pc00per : The problem is that if you assign action only to the middle or secondary mouse button, it also blocks the primary button, so if you want to grab, for example, scroll bar and you reached the edge of the monitor, the button will not work.
