### ISSUE TITLE
Inconsistent behavior between hot corners and clicks for expanded corners

### ISSUE THREAD

**Issue by UndeadDevel** [G-dH/custom-hot-corners-extended#22]
When two corners are expanded to the same side, the barrier size is correctly applied for the hot corner feature, but not for the click area...it seems the click area is actually split in half on that edge, while the extended hot corner barrier is not.

IMO, the most important thing is consistency, whichever solution is applied to both cases, but personally I would prefer the hot corner behavior to be used for both, i.e. that I can choose the percentage of the edge barrier size for both clicks and hot corner behavior with the slider, instead of the edge being split in half.

**Comment by G-dH** [comment]
It's both working correctly, just the implementation differs, these are two independent settings. The click area expands along the entire edge or half if the adjacent corner is set to expand in its direction. Hot corner barriers are adjustable with greater accuracy as it's more important to set them precisely.

**Comment by UndeadDevel** [comment]
Ah yes, I see now that I activated the visible edges...should have checked out the tool tips sooner! It indeed makes sense to implement it this way; closing.
