### ISSUE TITLE
Workspace indicator not displaying consistently in the same place

### ISSUE THREAD

**Issue by UndeadDevel** [G-dH/custom-hot-corners-extended#23]
Found another issue: when the workspace indicator is set to "Overlay Index" and I map mouse scrolling on some corner to workspace switching then the workspace indicator will display at the left side of the monitor for the first switch, but at the center of the monitor for subsequent switches if they occur in quick succession...if there is a pause then the first switch will again have the indicator on the left.

When switching workplaces from within the AATWS the indicator is always in the center, even on the first switch.

**Comment by G-dH** [comment]
Yes, I solved this issue in AATWS where it's crucial and didn't update the indicator in CHC-E yet.
