### ISSUE TITLE
Original Hot Corner still remains

### ISSUE THREAD

**Issue by UndeadDevel** [G-dH/custom-hot-corners-extended#24]
A really small issue, so no problem if there's no fix:

The original hot corner (top left) with it's "Show Activities Overview" and the ripple animation still remains even if that corner is set to something else and the animation switched off. In order to prevent accidentally triggering that, the hot corner barrier on my monitor needs to be set to "2" for both edges, though I don't remember if that was the default in the extension settings. If set to "1" then there will occasionally be cases of accidentally triggering the wrong function on that corner.
So maybe if this cannot be fixed properly the default for the edge extension could simply be set to "2" if it isn't already.

**Comment by G-dH** [comment]
Try to disable the original corner in gnome tweaks app, the new version of CHC-E in the repository does this automatically.

**Comment by UndeadDevel** [comment]
That fixes it, closing.
