### ISSUE TITLE
Application Grid opens another then the original in POP OS

### ISSUE THREAD

**Issue by filipepcapulo** [G-dH/custom-hot-corners-extended#31]
Thank's for this tool, it's really good for me.
The problem i found using Pop OS 21.10 is selecting the action "Application Grid" opens another menu of apps different of the POP OS menu.
There's a way to open the original Pop OS menu through this extension?

**Comment by G-dH** [comment]
Hi, the Pop Os uses a heavily customized Gnome Shell, I'll take a look at it and let you know.

**Comment by G-dH** [comment]
It's standalone application with its own launcher, so choose `Run Preset Command / Activate App ...` action and enter 'pop-cosmic-applications.desktop' into the revealed entry field. Tested.

**Comment by G-dH** [comment]
Actually, it's not a standalone app, the launcher executes js code inside GS via d-bus call. It's not what I'd expect... Anyway, that doesn't change the fact that it helped to solve this problem :)
