### ISSUE TITLE
Can't specify command or app in custom menu for "Run preset command/app" option

### ISSUE THREAD

**Issue by Haptein** [G-dH/custom-hot-corners-extended#32]
Thanks for working on this! This extension is super handy! Now moving on to the issue, currently there's no way to specify a command or application to be run within the custom menu customization.

**Comment by G-dH** [comment]
Hi, thanks for the input. It would be complicated to implement and frankly, I don't see a reason to have applications in the CHC-E custom menus. When it comes to commands and scripts, I think it's also task for other extension, like [Guillotine](https://extensions.gnome.org/extension/3981/guillotine/)...
