### ISSUE TITLE
Suggestion: Provide `make all` or `make locale` option

### ISSUE THREAD

**Issue by FiestaLake** [G-dH/custom-hot-corners-extended#36]
Either of them is required to make a fine PKGBUILD for aur package without useless zipping/unzipping process to get actual extension files.

**Comment by FiestaLake** [comment]
Note: Also I guess you didn't add an empty end line (for unix-friendly)

Ofc, I can do 
```
echo '
all: $(ZIP_CONTENT)' >> Makefile
```
for the option in PKGBUILD.
But it would be great if you integrate the option inside your Makefile.

**Comment by G-dH** [comment]
Feel free to send me a PR with changes you need.

**Comment by FiestaLake** [comment]
https://github.com/G-dH/custom-hot-corners-extended/commit/f0259278d702615fd2dfa9046aa45fe74980b6aa is a really nice commit for this, thanks!

I will consider making PR for `make locale` soon.
