### ISSUE TITLE
Hot corner not disabled with a full screen application.

### ISSUE THREAD

**Issue by nakrule** [G-dH/custom-hot-corners-extended#38]
With Gnome 42, hot corners are still active with a full-screen application (like a game). This is probably due to Gnome 42 and not this extension, although I'm not sure.

**Comment by G-dH** [comment]
Did you disable the corner triggers for fullscreen mode? The switches beside each action trigger menu should be inactive.

**Comment by nakrule** [comment]
That fixed it. Sorry for the inconvenience.
