### ISSUE TITLE
CHC-E settings: Facilitate scrolling within selection menu.

### ISSUE THREAD

**Issue by seltzered** [G-dH/custom-hot-corners-extended#39]
I love using CHC-E, just noticed the configuration menu for selecting actions doesn't seem to allow scrolling which can be a challenge on smaller display sizes. 

![image](https://user-images.githubusercontent.com/297435/166452732-13c9c1a1-86dc-4a4a-9ca5-8fa619901fa6.png)

**Comment by G-dH** [comment]
Yeah, this is a known bug in GTK4 and I'm really surprised it took a whole year for somebody to point out this issue here.
But I was faster and the latest CHC-E available in the GitHub repository has brand new TreeView based action chooser and the prefs window also starts more than 10x faster.

**Comment by seltzered** [comment]
Awesome! Will close then.
