### ISSUE TITLE
GameMode integration

### ISSUE THREAD

**Issue by mikefogit** [G-dH/custom-hot-corners-extended#41]
Hi

Is there a common/standard way of disabling the extension (and leaving default hot corner off) when GameMode starts?

Thanks.

**Comment by G-dH** [comment]
Hi, CHC-E has no support for GameMode, only offers action to lock direct hot corners so you can make the hot corner triggers irresponsive without the Shift key pressed. You can bind the action to a keyboard shortcut.

**Comment by mikefogit** [comment]
thank you.
