### ISSUE TITLE
Hot corners still work in full screen and games

### ISSUE THREAD

**Issue by taiwbi** [G-dH/custom-hot-corners-extended#42]
When I open a game, my mouse disappears and I can move the game view with the mouse, but apparently my mouse is just hidden and sometimes it reaches corners. If I don't have the extension disabled, the hot corners still work and I get kicked out of the game!!!!
I also had this problem with the Ubuntu dock. When my mouse reaches the bottom of the screen, the dock appears, but this doesn't happen in full screen mode, so I think this problem can be fixed at least in full screen mode.

**Comment by G-dH** [comment]
You can disable each hot corner for the fullscreen mode individually (the toggle button next to the action button) and the second option you have is to use option `Direct hot corner triggers require Shift` which allows you to block all hot corners at once only if you need it (Shift key needs to be pressed to activate hot corner). This option is controllable by the `Toggle Hot Corners Require Shift` action from the  `CHC-E Preferences` section so you can bind the action to a keyboard shortcut and toggle the option easily on and off when you need it.
![Screenshot from 2022-06-13 23-00-16](https://user-images.githubusercontent.com/73719686/173516370-e2a96bf0-7ba8-4c12-b67d-280d67fc859d.png)
![Screenshot from 2022-06-14 09-11-00](https://user-images.githubusercontent.com/73719686/173516401-3883f924-af88-44bd-b30f-e93e3049595b.png)
![Screenshot from 2022-06-14 09-10-14](https://user-images.githubusercontent.com/73719686/173516419-1f1d9925-2c49-4f94-aef1-6b263a35ab13.png)

**Comment by pc00per** [comment]
Can be closed ;)

**Comment by taiwbi** [comment]
Thank you :) I didn't see that option
