### ISSUE TITLE
Reverse mouse position after switching workspace

### ISSUE THREAD

**Issue by ForteDexe** [G-dH/custom-hot-corners-extended#43]
I use hot edge to switch workspace, the problem is it kept the mouse position of a previous workspace. It would be nice if we have a feature to reverse the mouse position after switching a workspace.
Btw, tks for this awesome tool, I was looking for this for a long time.

**Comment by G-dH** [comment]
Thanks for the feedback. I understand your request, I'll think about it.

**Comment by G-dH** [comment]
Sorry, I will not add this option. Too much work (to do it right) for a feature for one or two users ;)
