### ISSUE TITLE
support for auto-detection of other extension panel items

### ISSUE THREAD

**Issue by pc00per** [G-dH/custom-hot-corners-extended#45]
Using [clipboard extension](https://github.com/SUPERCILEX/gnome-clipboard-history) & donno how to add it into hot corners menu. Lil bit of help would be appreciated. Already [asked this there btw](https://github.com/SUPERCILEX/gnome-clipboard-history/issues/88).

**Comment by SUPERCILEX** [comment]
If I had to guess, you need to do something like this https://github.com/G-dH/custom-hot-corners-extended/blob/3117ab994565e84630c4ba201d3b13eea0bcee1a/src/extension/actions.js#L932 but with our indicator name: https://github.com/SUPERCILEX/gnome-clipboard-history/blob/9a5bdefd240b9a7ff3311bde6a2c8995c26898fa/extension.js#L1267

**Comment by pc00per** [comment]
> If I had to guess, you need to do something like this
> 
> https://github.com/G-dH/custom-hot-corners-extended/blob/3117ab994565e84630c4ba201d3b13eea0bcee1a/src/extension/actions.js#L932
> 
> but with our indicator name: https://github.com/SUPERCILEX/gnome-clipboard-history/blob/9a5bdefd240b9a7ff3311bde6a2c8995c26898fa/extension.js#L1267

I believe there's lot more coding required than that. There must be some way to detect if there are any other panel elements added via other extentions. And then show up / update them in the menu list of hot-corners. @janxyz ?

**Comment by G-dH** [comment]
The auto-detection is complicated because prefs code has no access to the shell, so the information must be collected by the extension which has to make that data accessible to the prefs. Then prefs needs to store the action for a trigger with additional parameter identifying the panel button. Not worth the effort for me..

**Comment by pc00per** [comment]
Is it possible to write auto-detection as a node.js backend ? With something like child process exec ?

**Comment by G-dH** [comment]
You need to run the code inside the Shell, as an extension, to have access to the internals of the panel.
