### ISSUE TITLE
Doesn't work on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by salexfo** [G-dH/custom-hot-corners-extended#48]
Hi, 
Can't make the extension work on Ubuntu 22.04 when I switch from gnome-session to unity

**Comment by G-dH** [comment]
It's extension of GNOME Shell, not Unity.

**Comment by salexfo** [comment]
This is what I get on the terminal:
alex@alexander-new-hp:~$ echo $XDG_CURRENT_DESKTOP
ubuntu:GNOME

**Comment by G-dH** [comment]
If you're running Unity, you cannot use extensions for GNOME Shell, because GNOME Shell is not running ;)

**Comment by G-dH** [comment]
Can I close this issue or am I misunderstanding your problem?
If you installed Unity and logged in the Unity Session, then GNOME Shell with extensions is out of the game. If you log into Ubuntu GNOME session, then the extension should work.

**Comment by salexfo** [comment]
Frankly I'm not sure how unity shell works, if I have a gnome desktop can I still open unity session?

**Comment by G-dH** [comment]
Unity is based on completely different code (Compiz) which has nothing common with the the GNOME Shell, but both are doing the same job. GNOME Shell extensions cannot run as standalone applications, they are actually patches for the Shell's code, replacing its parts and adding new ones. If you use Unity, then you can use `Unity Tweak Tool` app to assign basic actions to hot corners and edges. Another options brings `CompizConfig Settings Manager` which gives you access to installed Unity extensions. Look here: [Can I set Hot Corners to run custom commands in Unity?](https://askubuntu.com/questions/884718/can-i-set-hot-corners-to-run-custom-commands-in-unity)

**Comment by salexfo** [comment]
@G-dH well, since I do have *gnome* tweak tool and the output above I belive it's gnome, no? However, on Ubuntu 22.04 login screen I have a selection between Gnome and Unity. However I can use the gnome-tweak-tool and alex@alexander-new-hp:~$ echo $XDG_CURRENT_DESKTOP
outputs gnome. Hence I'm a bit puzzled.

**Comment by G-dH** [comment]
Why would you even log into Unity session if you want to use GNOME Shell? Do you see Unity on your Desktop? Then you're running Unity and cannot use GNOME extensions. Do you see GNOME Shell? Then the extension should work.

**Comment by salexfo** [comment]
OK, I see that I need to do some research to understand first of all *what* am I using. Once I do this I'll be able to tell how to solve the issue and whether the extenstion should work. Thank you for your time. Closing.

**Comment by G-dH** [comment]
If you press Super (Windows) key after you log in, you'll see what you're using. You can check on the web what both shells look like, there is a big difference.
You can also check if the GNOME Shell is running:
`ps ax |egrep '/usr/bin/[g]nome-shell' && echo yes || no`

**Comment by salexfo** [comment]
alex@alexander-new-hp:~/Downloads$ ps ax |egrep '/usr/bin/[g]nome-shell' && echo yes || no
  31562 ?        Ssl   22:02 /usr/bin/gnome-shell
yes

**Comment by G-dH** [comment]
Well..
1. If you log into GNOME session, the extension works?
2. If you log into Unity session, you still have the same desktop environment as in GNOME session?
3. Why would you want to run Unity session then?
4. How did you achieve this?
