### ISSUE TITLE
Right side to activate/hide mp3 player

### ISSUE THREAD

**Issue by vitalfadeev** [G-dH/custom-hot-corners-extended#52]
Right side hot area to activate/hide mp3 player.
Like on screen
1. ![Снимок экрана от 2022-09-03 17-46-03](https://user-images.githubusercontent.com/24979554/188267281-de74f4e2-e1af-4449-9e14-1fde6140f9c2.png)
2. ![Снимок экрана от 2022-09-03 17-56-29](https://user-images.githubusercontent.com/24979554/188267336-52d4bea6-1400-49f6-b02a-f315fcafcc65.png)

Please. Thank!

**Comment by G-dH** [comment]
Sorry, I'm not going to add hot edges.
