### ISSUE TITLE
Try this

### ISSUE THREAD

**Issue by vitalfadeev** [G-dH/custom-hot-corners-extended#53]
Try this configuration:
Left up corner - Open ArcMenu
Right up corner - Close active window
Left down - run nautilus
Right down - switch window

![Снимок экрана от 2022-09-03 18-00-00](https://user-images.githubusercontent.com/24979554/188267522-47497e83-00c1-4483-a34b-29cb06d2fe21.png)
![Снимок экрана от 2022-09-03 18-01-04](https://user-images.githubusercontent.com/24979554/188267526-9f6c7135-a595-4a4a-826e-ef1cd3c8783b.png)
![Снимок экрана от 2022-09-03 18-01-06](https://user-images.githubusercontent.com/24979554/188267529-621d615e-4978-4ccc-90b0-52882630d031.png)
![Снимок экрана от 2022-09-03 18-01-09](https://user-images.githubusercontent.com/24979554/188267532-371113ac-0053-424e-8bc2-2bbbe82f7768.png)
![Снимок экрана от 2022-09-03 18-01-12](https://user-images.githubusercontent.com/24979554/188267537-7fc0550d-74dc-4301-ac87-83a1509a2224.png)
![Peek 2022-09-03 18-05](https://user-images.githubusercontent.com/24979554/188267618-ebd61a75-0770-45c2-95bc-3b5e98a41aa7.gif)

**Comment by G-dH** [comment]
What's the point?

**Comment by G-dH** [comment]
That doesn't look like a bug report or a feature request.
