### ISSUE TITLE
RENAME the extension for use with RHEL9, Almalinux9...

### ISSUE THREAD

**Issue by klausbu** [G-dH/custom-hot-corners-extended#54]
RHEL 9 and clones like AlmaLinux 9 allow only the following 3 signs to be part of an extension`s name:  .  _ @

So the extension should be named: custom_hot_corners_extended@G_dH.github.com to work with RHEL 9...

see 11.1: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/desktop_migration_and_administration_guide/gnome-shell-extensions

The uuid identifier is globally-unique. When choosing it, remember that the uuid must possess the following properties to prevent certain attacks:

    Your uuid must not contain Unicode characters.
    Your uuid must not contain the gnome.org ending as it must not appear to be affiliated with the GNOME Project.
    Your uuid must contain only alphanumerical characters, the period (.), the at symbol (@), and the underscore (_).

**Comment by G-dH** [comment]
Different uuid means different extension, that would be a big complication. You can edit the `uuid` in your installation's `metadata.json` file if you need to.
