### ISSUE TITLE
Slider for brightness/contrast

### ISSUE THREAD

**Issue by fastrizwaan** [G-dH/custom-hot-corners-extended#55]
Bro, there are many options, which need Sliders. Like Brightness, etc.

Just like show menu, please add slider to change the brightness/contrast etc. values. 

I'm using shortcuts currently to increase/decrease brightness, but it becomes easy if we could have slider. 

Thank you.

**Comment by G-dH** [comment]
Thanks for the input. If I add sliders it will be implemented as a `custom menu` item.

**Comment by G-dH** [comment]
I forgot to mention here that I've added OSD level indicators for brightness, contrast and opacity. You can assign up/down actions of the effects to scroll triggers of any corner or edge and control the level using the mouse wheel or touchpad swipes.
