### ISSUE TITLE
First scroll tick of the mouse wheel is always ignored

### ISSUE THREAD

**Issue by spupy** [G-dH/custom-hot-corners-extended#58]
I try to configure mouse wheel up/down in the extended top right corner to switch workspace. The particular action and screen corner are actually irrelevant.

**Problem**: 
When I move the mouse to the configured corner and start scrolling, the first scroll "tick" of the mouse always gets ignored. All mouse wheel inputs afterwards work as expected, until I remove the mouse from corner. It doesn't matter what direction the first scroll is, it doesn't get queued or anything and only the subsequent scroll inputs are registered.  

Click events work as expected. With "Ctrl" enabled for the actions, the first scroll is still ignored.

The problem only exists with a mouse. With touchpad I can't replicate it, but I suspect that the touchpad simply send multiple scroll inputs.
I'm trying to replace the extension "Top Panel Workspace Scroll", which itself doesn't have this problem.

**System & Software**:
Ubuntu 22.04.1 LTS
Gnome 42.5, running on X11
Tested with extension version 23 and no other extensions enabled, fresh after login.
All settings in the "Options" page are turned off, minimum delay is set to 100ms. Only mouse wheel up/down configured for the specific corner.
Toggling the multitasking settings in Ubuntu's Settings has no effect.

**Comment by G-dH** [comment]
Thanks for the report! I grabbed a mouse without smooth scrolling and now I can reproduce the bug. So I fixed one bug to create another one.. I'll fix it soon.

**Comment by G-dH** [comment]
You can try updated version from the GitHub repository, the issue should be fixed.

    git clone https://github.com/G-dH/custom-hot-corners-extended.git
    cd custom-hot-corners-extended
    make install

**Comment by spupy** [comment]
It works as expected. Thanks a lot!
