### ISSUE TITLE
Window flickers when using any window ! 

### ISSUE THREAD

**Issue by neeswebservices** [G-dH/custom-hot-corners-extended#59]
Basically when there is some application opening behind the scene and we have opened the another application in the top which is previewing via full screen. when we try to minimize via the corner it shows the flickering for a while and feels so ugly and embarrassing to watch !

**Comment by G-dH** [comment]
Embarrassing is the style of your report, dude, I'm not your little brother.
The issue with minimizing full-screen windows is a bug in GNOME Shell, CHC-E has nothing to do with it, it just calls the built-in minimize function. However, I've fixed this issue it in the _[V-Shell](https://github.com/G-dH/vertical-workspaces)_ extension, you can try it.
