### ISSUE TITLE
"Open Panel Date Menu" doesn't close on second mouse action.

### ISSUE THREAD

**Issue by lb-d** [G-dH/custom-hot-corners-extended#61]
When I open application or overview I can hit the same corner again to close it but that doesn't happen  when I choose "Open panel date menu" or "Open panel app menu". And when "Open panel system menu" is chosen it will open system menu on first action then date menu on the second. I'm not sure if this is by design.

 I run gnome 3.38 on Debian 11.

**Comment by G-dH** [comment]
Unfortunately menus grab all input and even hot corner triggers are blocked when the menu is open.

**Comment by lb-d** [comment]
Thanks for letting me know. And thanks for the great extension.
