### ISSUE TITLE
Recent version (25) stops working after some time

### ISSUE THREAD

**Issue by sojusnik** [G-dH/custom-hot-corners-extended#62]
After the update to the recent version (25) the extensions stops working after some time. When going to https://extensions.gnome.org/local/, then "ERROR" appears besides the extension. Was using this extension for roughly 1 month and never experienced this issue. Only after updating it to v25, this issues appeared a second time today.

Restarting Gnome (Alt+f2, then r) solves this issue temporarily.

What's the best way to debug this?

I'm on Ubuntu 22.10 with Gnome 43.1.

**Comment by G-dH** [comment]
Hmm, looks like I didn't fix what I thought I fixed... Just enable the panel menu or don't use screen lock ;) I'll fix it in a bit...

**Comment by G-dH** [comment]
Fixed in the repo, on e.g.o soon..

**Comment by sojusnik** [comment]
Perfect! New version already available!
