### ISSUE TITLE
Icon in tray that cannot be disabled

### ISSUE THREAD

**Issue by MaxBrandtner** [G-dH/custom-hot-corners-extended#64]
Please either remove the icon altogether or at least add an option to remove it

**Comment by G-dH** [comment]
Open settings window and disable it on the _Options_ tab.

**Comment by GinoMalatesta** [comment]
The option to disable it has vanished ... please bring it back.
Could it be set with a command?

**Comment by G-dH** [comment]
What has vanished? The option _Show Panel Menu_ from the _Options_ tab of Settings window?
What version of CHC-E do you use?

**Comment by GinoMalatesta** [comment]
Yes, it's gone, version 24.

**Comment by G-dH** [comment]
Then it's gone because you downgraded from version 25 to 24 instead of upgrading to the latest 26, for some reason.

**Comment by GinoMalatesta** [comment]
I see. I didn't downgrade, I was prompted for an update and that's what I got. Strange, I'll remove it and install it again then, thx.

**Comment by GinoMalatesta** [comment]
It's back now, thank you!
