### ISSUE TITLE
Option to change behavior of hot corner while in Application Grid view

### ISSUE THREAD

**Issue by tomorrow-539** [G-dH/custom-hot-corners-extended#66]
Hello.  I was wondering if it would be possible to add an option to choose the desired behavior when you use a "Show Activities Overview" hot corner while the Application Grid is open.  

If I'm viewing the Application Grid and I use my hot corner, I would prefer that it returns me to the desktop.  I could swear that's how it was working until recently, but I could be wrong.  Currently if I'm viewing the Application Grid and I use my hot corner, it takes me to the Activities Overview, and then I have to use the hot corner again to return to the desktop.  

Out of curiosity, I disabled CHC-E and tried Gnome's built in hot corner while viewing the Application Grid to see what the default behavior is, and it returned me to the desktop as expected.  The Super key does the same as well.

It's an extremely minor thing, and I can easily work around it if necessary, but I figured it couldn't hurt to ask.  

By the way, I just realized that in my setup I'm using 3 extensions developed by you (CHC-E, AATWS, and Vertical Workspaces).  All three of them are excellent!  Thank you for your awesome work, it's very much appreciated!

**Comment by G-dH** [comment]
Hello, thanks for your kind words. You're right, I changed the behavior during refactoring because it works better for me since I use one corner for the overview and the second one for app grid. I can add an option to change the behavior for both actions.

**Comment by G-dH** [comment]
I did it the easiest way - the action list now has options starting with _Toggle_ for you and _Show_ for me. Available in the GitHub repository.
