### ISSUE TITLE
Slow Response for Running Preset Command

### ISSUE THREAD

**Issue by DarylO71** [G-dH/custom-hot-corners-extended#72]
I have my upper right corner configured to run the preset command "xdotool key ctrl+shift+n", and it used to be instantaneous, but not anymore.  I don't know what happened, but the delay is just not tolerable.  There have been updates to my system, but I don't know what could be causing the delay.  The actual keystroke works just as instantly as it had before.  Does anyone have a clue how I could fix this?  Thanks!

**Comment by G-dH** [comment]
Does this issue persist?

**Comment by DarylO71** [comment]
No.  I had to switch to another command (xte 'keydown Control_L' 'keydown Shift_L' 'key g' 'keyup Control_L' 'keyup Shift_L') to avoid the delay.  Following your message, I switched back to the original command and it's working fine now.

**Comment by G-dH** [comment]
Thanks for the info.
