### ISSUE TITLE
Quick settings appear left instead of right when window is full screen or when top bar is hidden

### ISSUE THREAD

**Issue by Jegah** [G-dH/custom-hot-corners-extended#76]
When a window is full screened (for example firefox using f11) or when the top bar is hidden by using an extension like "just perfection", then the "Open panel system menu" toggle will open the quick setting menu in the top left corner instead of the right corner

**Comment by G-dH** [comment]
Thanks, I will try to "fix" this for the next release.

**Comment by G-dH** [comment]
Fix is available in the repository, menus will always open at the mouse pointer position, even if the panel is visible.
