### ISSUE TITLE
Activate Screensaver hot corner option isn't working.

### ISSUE THREAD

**Issue by Ceqell** [G-dH/custom-hot-corners-extended#77]
Ubuntu 20.04 LTS, I installed the GNOME extension and selected the activate screensaver hot corner function, but doesn't work, every other option still works from what I've tested, happy to provide for technical details, I'm still a noob to linux :/

**Comment by Ceqell** [comment]
Update: Nope I actually did something wrong, the thing I was using was xscreensaver, not gnome-screensaver. Man.

**Comment by G-dH** [comment]
CHC-E doesn't support xscreenserver, but if you can activate it from command line, you can use that command with the `Run Preset Command` action.

**Comment by Ceqell** [comment]
> CHC-E doesn't support xscreenserver, but if you can activate it from command line, you can use that command with the `Run Preset Command` action.

So that's why it still doesn't work for me after the fix, well thanks for informing me; I'll use the ``Run Present Command`` action

**Comment by Ceqell** [comment]
I found it! For anyone reading this and absolutely struggling, the command is ``xscreensaver-command --lock``, a lot of digging but worth it. Albeit the application will ask for your user password if you want to exit the screensaver and back to whatever you were doing before this. Hitting the "New Login" button will send you to the main login page.
