### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by GerryT11** [G-dH/custom-hot-corners-extended#78]
There are breaking changes which will require a separate extension release for Gnome 45 and <=44:

See Gnome 45 porting guide: https://gjs.guide/extensions/upgrading/gnome-shell-45.html

FYI, here is lots of information on the changes in Gnome 45 for extensions: https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/ . For early testing, they mention "You can test your extensions by downloading the latest [GNOME OS](https://os.gnome.org/) and trying your extension there."

**Comment by GerryT11** [comment]
> You can help me with testing:
> 
> [Installation instructions for GNOME 45](https://github.com/G-dH/custom-hot-corners-extended/tree/esm-modules#installation-from-source)

Sorry, so far I was not yet able to successfully run GnomeOS in Gnome-Boxes to test the extension. 
I hope someone else helps you with testing, too!

**Comment by G-dH** [comment]
@GerryT11 Boxes and GNOME OS never worked well on my system, I'm testing on Fedora Rawhide and 39 in VirtualBox.

**Comment by LostinSpacetime** [comment]
> You can help me with testing:
> 
> [Installation instructions for GNOME 45](https://github.com/G-dH/custom-hot-corners-extended/tree/esm-modules#installation-from-source)

I tested with Fedora 39 in VMware and so far, it worked perfectly. The only issue is that it works only with ”Use fallback hot corner triggers” but I believe it's because of how VMware handles mouse input.

**Comment by G-dH** [comment]
@LostinSpacetime Thanks! Hot corners can't work inside the virtual machine if mouse integration is enabled.

**Comment by LostinSpacetime** [comment]
I disabled the automatic mouse grabbing/releasing by adding mks.gamingMouse.policy = "gaming" to the vm. The mouse stays now locked within the guest window, but even like this only the fallback trigger works.

**Comment by G-dH** [comment]
I don't use VMware so I can't say, but it works as expected inside the VirtualBox.

**Comment by LostinSpacetime** [comment]
This is what I get when I disable the Extension:

Main.layoutManager._updateHotCorners is not a function

After a restart, the Gnome native active corner works as expected.

**Comment by G-dH** [comment]
Thanks, I'll look into it.

**Comment by G-dH** [comment]
> Main.layoutManager._updateHotCorners is not a function

Should be fixed.

**Comment by LostinSpacetime** [comment]
The error is gone, and I also tested within VirtualBox. The extension is working, as far as I can tell. It seems the problem I have is VMware related.

Thank you!

**Comment by belarios** [comment]
Mostly working for me on arch linux, gnome 45.0.

Pressure barrier sensitivity changed somehow. I used to have them at 100, but with the esm branch that didn't work at all. Took me a while to figure out that I had to move them down below 20 to get them to be responsive.

I've had one gnome-shell crash so far while pressing the side of the screen. Will update if it happens again.

Thanks.

**Comment by G-dH** [comment]
@belarios Nothing has changed in the CHC-E in this regard, and the hot corner triggers work the same for me on the GS 45 with the same pressure setting as the 44, so the difference must be somewhere else..

**Comment by mlmilliman** [comment]
> > Main.layoutManager._updateHotCorners is not a function
> 
> Should be fixed.

I'm still receiving this error with GNOME 45 on Ubuntu.

**Comment by marekzan** [comment]
> Mostly working for me on arch linux, gnome 45.0.
> 
> Pressure barrier sensitivity changed somehow. I used to have them at 100, but with the esm branch that didn't work at all. Took me a while to figure out that I had to move them down below 20 to get them to be responsive.
> 
> I've had one gnome-shell crash so far while pressing the side of the screen. Will update if it happens again.
> 
> Thanks.

I have the same issue. I had to lower the sesitivity belo 20. On my machine the sweet spot is at about 10.

**Comment by G-dH** [comment]
@marekzan Thanks, I'll look into it. Can you please try, for example, the _Hot Edge_ extension to see whether it has the same issue?

**Comment by marekzan** [comment]
I just tried the [Hot Edge](https://extensions.gnome.org/extension/4222/hot-edge/) extension and it worked with its defaults. 

Activation Pressure: 150
Edge Size: 100

**Comment by G-dH** [comment]
@marekzan , @belarios  I missed a reference to the unexported HOT_CORNER_PRESSURE_TIMEOUT constant. Can you please try the latest update?

**Comment by marekzan** [comment]
I tried the latest update and can confirm that it fixed the issue for me. Thank you very much for your effort!

**Comment by FelixFourcolor** [comment]
I tried on Arch. Everything seems to work.

**Comment by FelixFourcolor** [comment]
Is there any reason you haven't published this to EGO? Not that I have any problem with the git version, I'm just curious.

**Comment by G-dH** [comment]
@FelixFourcolor One reason is my free time and the other is the fact that CHC-E breaks the new EGO rules that affect actions creating screen/window effects and objects that must survive screen lock.
