### ISSUE TITLE
Suggestion: Top Middle "Hot Corner" and Top Right "Hot Corner" for elements of the gnome shell UI

### ISSUE THREAD

**Issue by duartec3000** [G-dH/custom-hot-corners-extended#8]
Saw your post on Reddit, fantastic extension, thank you so much for this gift to the community.

Since GNOME 3.0 that I find the Top Left Hot Corner brilliant, as a heavy high DPI mouse user this as become my preferred way of  opening the Activities Overview.

But I always wondered why didn't GNOME extend the Hot Corner functionality to other highly frequented UI Elements: The Top Middle Notification/Calendar and the Top Right System Menu.

My suggestion or question is would it  be possible to add this functionality to this extension?
- A top middle "hot corner" that opens the notification center
- An option for the top right "hot corner" to open the system menu

Maybe you can make a dream come true?
Many thanks for all your hard work so far!

**Comment by G-dH** [comment]
Thank you for your kind words. Adding these actions is possible but adding the dedicated edge triggers is beyond the concept of this extension as is set now. Even though I actually thought about it for a while. You can use both top corners and expand them horizontally along the top edge. You can expand bottom hot corners vertically to get the triggers closer to the top panel. That's all I can offer for now.
