### ISSUE TITLE
CHCE can't be activated in GNOME Shell: 45.1

### ISSUE THREAD

**Issue by marcgloor** [G-dH/custom-hot-corners-extended#84]
Hi chaps, 

My CHCE on/off switch in gnome extensions panel can't be switched on/off and remains inactive after extension installation using the gnome extension page. 

CHCE version: 45.2
GNOME Shell: 45.1
Firefox: 121.0.1 (64-bit)
Ubuntu: 23.10

I pulled latest CHCE and Ubuntu gnome versions. Does CHCE and Gnome Shell version need to be same version as I couldn't download a CHCE v45.1? Any clue what I could do?

Marc

**Comment by G-dH** [comment]
@marcgloor Is it still an issue? Any error displayed in the Extensions app or on the e.g.o web page?

**Comment by marcgloor** [comment]
No clue what happened but after reinstalling gnome shell and CHCE, all worked fine. Coulnd't reproduce the issue so this tread can be closed.
