### ISSUE TITLE
Trigger a corner on hover instead of click

### ISSUE THREAD

**Issue by jacket** [G-dH/custom-hot-corners-extended#85]
I've been trying to configure my bottom right corner to show the desktop on hover. However, it seems that hot corners are activated on click. Have I understood correctly that it is not possible to trigger the action by moving the cursor into the corner?

**Comment by G-dH** [comment]
If you assign an action to the mouse button click, it reacts on the click. If you assign an action to the hot corner trigger, then it should react to pressure on the corner.

**Comment by jacket** [comment]
These are my settings to trigger an action on hover in the bottom corner. Nothing happens on hover or click:

![image](https://github.com/G-dH/custom-hot-corners-extended/assets/54663/90c11ad7-816a-42a0-a94a-607bccfcdc63)

**Comment by G-dH** [comment]
Any other extensions enabled? Is it running in a virtual machine? There is also the "Use fallback hot corners" option in case hot corner barriers don't work.

**Comment by jacket** [comment]
I found the problem - the extension was disabled in the list of Extensions here:

![image](https://github.com/G-dH/custom-hot-corners-extended/assets/54663/0ac52cac-d916-45bb-a979-a08db849ea2a)

I enabled it and the hot corners are working perfectly.

Sorry for the user error!
