### ISSUE TITLE
Suggestion: Add move window capability as well (similar to shift it)

### ISSUE THREAD

**Issue by haydonryan** [G-dH/custom-hot-corners-extended#87]
Thankyou for a great extension! So far seems to work well, and doesn't crash (which is a problem with other gnome extensions I've found.)

I installed this to get keyboard shortcuts missing from base gnome.  

On the mac I used to use a tool called shift it - which allowed you to move windows around.  You have an option to move a window to a new monitor and workspace, but not within the monitor / workspace.  

Currently Gnome only offers left, right split, maximize and restore, but you could offer 2/3 1/3 split, (awesome for large monitors), and also horizontal splits...
My preferences on shiftit were:
hyper up - move to top half of screen (repeated pressing would cycle 1/2, 1/3 and full screen.
hyper down - move to bottom half of screen (repeated pressing would cycle 1/2, 1/3 and full screen.
hyper left - move to left half of screen (repeated pressing would cycle 1/2, 1/3 and full screen.
hyper right - move to right half of screen (repeated pressing would cycle 1/2, 1/3 and full screen.
hyper m - move to other screen.

but i wished they'd also include the ability to use hyper and the keypad to split a monitor into 3x3 grid.

Have a great day!

**Comment by G-dH** [comment]
Thanks for your feedback. CHC-E can do a lot, but it's not a tiling assistant. GNOME Shell provides Super+Left/Right to resize windows to half of the screen, and if you want more, consider trying some tiling extension.

**Comment by haydonryan** [comment]
Totally understand. :) closing.
