### ISSUE TITLE
Opening Firefox disables all my gnome-extensions

### ISSUE THREAD

**Issue by jnk5y** [G-dH/custom-hot-corners-extended#9]
**Linux distribution and version**
Fedora 34

**GNOME Shell version**
GNOME Shell 40.2

When I install custom-hot-corners-extended (this is in the last 2 or so days, worked find before) and open firefox all my gnome-extensions get disabled. I just enabled it while firefox was running and had no issue. Closed firefox and reopened it and still no issue. Seems to only happen when firefox first opens on my system.

`journalctl /usr/bin/gnome-shell --since "2 days ago" |grep corners-extended` gives me this

> gnome-shell[63140]: JS ERROR: Extension custom-hot-corners-extended@G-dH.github.com: TypeError: this._getWindowSurface(...) is null
>                                                 _removeEffects@/home/jkyrus/.local/share/gnome-shell/extensions/custom-hot-corners-extended@G-dH.github.com/actions.js:113:18
>                                                 removeAllEffects@/home/jkyrus/.local/share/gnome-shell/extensions/custom-hot-corners-extended@G-dH.github.com/actions.js:92:22
>                                                 clean@/home/jkyrus/.local/share/gnome-shell/extensions/custom-hot-corners-extended@G-dH.github.com/actions.js:68:14
>                                                 disable@/home/jkyrus/.local/share/gnome-shell/extensions/custom-hot-corners-extended@G-dH.github.com/extension.js:104:13

**Comment by G-dH** [comment]
Thank you for the report. I have not experienced this problem yet, but I see the problem. Will fix it after the weekend.

**Comment by G-dH** [comment]
@jnk5y Can you please try the updated extension and let me know whether the issue persists?

**Comment by jnk5y** [comment]
All working as it should. Thanks!
