### ISSUE TITLE
Update to Gnome 46

### ISSUE THREAD

**Issue by KwkabCompany** [G-dH/custom-hot-corners-extended#90]
Please update to gnome version 46 in https://extensions.gnome.org

**Comment by LukaszH77** [comment]
I hoped adding 46 to shell-version in metadata.json will allow me to use this extension with GNOME 46, but sadly it doesn't work. All I got is `TypeError: global.display.supports_extended_barriers is not a function`

**Comment by G-dH** [comment]
The updated version is already available in this repository, installation instructions are an the [README](https://github.com/G-dH/custom-hot-corners-extended?tab=readme-ov-file#installation-from-source). I'll send it to e.g.o soon.

**Comment by LukaszH77** [comment]
Thank you!

**Comment by G-dH** [comment]
Version 46.0 is also available on the e.g.o site now.
