### ISSUE TITLE
[FEATURE REQUEST] add double trigger activate corner

### ISSUE THREAD

**Issue by JE-Amouel** [G-dH/custom-hot-corners-extended#93]
hi,
I always use my application windows in full screen, I use chc for two of the corners of my screen, at the top left, I trigger the activity overview, at the top right ,I trigger the quick setting menu,

the problem is  that, as the control buttons(minimize, full screen, close) of my window are on the right, like i always using full screen window, those button are near the top left corner, and by the fact, near the top left trigger point, so sometimes when moving my mouse towards the close button, I unintentionally trigger the left corner ,

Is it possible to add an independent double-check option for each corner?
the goal would be that each time my mouse reaches the trigger point, it would be necessary to left click to validate.

THANKS.

**Comment by G-dH** [comment]
Simply set the action to trigger with the left mouse button instead of assigning it to a hot corner. You can also disable the hot corner functionality for fullscreen mode.

**Comment by JE-Amouel** [comment]
that's why you're the architect of more than half, you're a genius.
I just didn't notice all the details of the CHC-E interface, even though you had already thought about it.

thanks for your quick response!.

**Comment by G-dH** [comment]
No problem :)
